import React, { useState } from 'react';
import { Activity, ArrowUpRight, BellRing, CheckCircle2, Clock3, HeartHandshake, MapPin, Megaphone, ShieldAlert, Truck, UsersRound } from 'lucide-react';
import { motion } from 'framer-motion';
import { useAuth } from '../context/AuthContext';
import { activities, alerts, requests, shelters } from '../lib/mockData';

export default function Dashboard() {
  const { session, can } = useAuth();
  const [tab, setTab] = useState('overview');
  const citizen = session.role === 'citizen';
  return <div className="content-stack">
    <motion.div className="hero-banner glass-panel" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><div><span className="eyebrow">{citizen ? 'Personal safety overview' : 'Operations overview'}</span><h2>{citizen ? 'Stay informed. Ask early. Stay safe.' : 'See the response network at a glance.'}</h2><p>{citizen ? 'Critical alerts, help requests and safe places are kept one tap away.' : 'Coordinate requests, shelters, volunteers and public messaging from one control layer.'}</p></div><div className="hero-banner-art"><div className="radar"><span/><span/><span/></div><div className="radar-label"><span className="live-dot"/> Network live</div></div></motion.div>
    {!citizen && <div className="stats-grid four">{[['Active incidents','07','+2 today',ShieldAlert],['Open requests','24','6 critical',BellRing],['Volunteers','186','+14 this hour',UsersRound],['Shelter capacity','71%','1,406 beds',MapPin]].map(([k,v,s,I])=><Metric key={k} label={k} value={v} sub={s} Icon={I}/>)}</div>}
    {citizen && <div className="stats-grid four">{[['Active alerts','03','2 near you',BellRing],['Help request','No active','Create request',HeartHandshake],['Closest shelter','12 min','642 / 850 occupied',MapPin],['Emergency line','112','Always available',ShieldAlert]].map(([k,v,s,I])=><Metric key={k} label={k} value={v} sub={s} Icon={I}/>)}</div>}
    <div className="section-tabs"><button className={tab==='overview'?'active':''} onClick={() => setTab('overview')}>Live overview</button><button className={tab==='activity'?'active':''} onClick={() => setTab('activity')}>Activity</button><button className={tab==='guides'?'active':''} onClick={() => setTab('guides')}>What to do now</button></div>
    {tab==='overview' && <div className="dashboard-columns"><Panel title="Priority alerts" icon={<BellRing size={17}/>}>{alerts.map((a,i)=><AlertRow key={a.id} alert={a} first={i===0}/>)}</Panel><Panel title={citizen?'Your nearby shelters':'Shelter network'} icon={<MapPin size={17}/>} action="View all"><div className="shelter-list">{shelters.slice(0,3).map(s=><div className="shelter-row" key={s.id}><div className="shelter-avatar"><MapPin size={15}/></div><div><strong>{s.name}</strong><span>{s.city} · {s.occupied}/{s.capacity} occupied</span></div><div className="capacity-bar"><i style={{width:`${(s.occupied/s.capacity)*100}%`}}/></div></div>)}</div></Panel></div>}
    {tab==='activity' && <Panel title="Live activity feed" icon={<Activity size={17}/>}><div className="activity-feed">{activities.concat(['Public campaign reach crossed 2.4M households']).map((a,i)=><div key={i}><span className="timeline-dot"/><div><strong>{a}</strong><small>{i<2?'Just now':`${i*7+3} min ago`}</small></div></div>)}</div></Panel>}
    {tab==='guides' && <div className="guide-grid">{[['During a flood','Move to higher ground. Avoid walking or driving through moving water.'],['If you need medicine','Create a medical request and mention the medicine, patient age and nearest landmark.'],['Helping others','Only enter registered response areas and follow instructions from incident commanders.']].map(([h,p],i)=><div className="guide-card glass-panel" key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p><button className="link-button">Read guidance <ArrowUpRight size={15}/></button></div>)}</div>}
    {!citizen && <div className="dashboard-columns"><Panel title="Assistance queue" icon={<Clock3 size={17}/>} action="Open requests"><div className="table-list">{requests.map(r=><div className="queue-row" key={r.id}><div><strong>{r.id}</strong><span>{r.type} · {r.location}</span></div><span className={`tag ${r.priority.toLowerCase()}`}>{r.priority}</span><span className="queue-status">{r.status}</span><strong>{r.team}</strong></div>)}</div></Panel><Panel title="Campaign pulse" icon={<Megaphone size={17}/>}><div className="campaign-pulse"><div className="pulse-number">2.4M</div><div><strong>Households reached</strong><span>Monsoon Ready Maharashtra</span></div><div className="mini-bars"><i/><i/><i/><i/><i/></div></div><div className="campaign-foot"><span>+18% this week</span><b>On target</b></div></Panel></div>}
  </div>;
}
function Metric({label,value,sub,Icon}){return <motion.div className="metric glass-panel" whileHover={{y:-3}}><div className="metric-icon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong><small>{sub}</small></motion.div>}
function Panel({title,icon,action,children}){return <section className="panel glass-panel"><div className="panel-head"><div><span className="panel-icon">{icon}</span><strong>{title}</strong></div>{action&&<button className="link-button">{action}<ArrowUpRight size={14}/></button>}</div>{children}</section>}
function AlertRow({alert,first}){return <div className={`alert-row ${first?'primary':''}`}><span className={`severity-dot ${alert.level}`}/><div><strong>{alert.title}</strong><span>{alert.region}</span><small>{alert.body}</small></div><b>{alert.time}</b></div>}
