import React, { useState } from 'react';
import { CheckCircle2, HeartPulse, Home, Info, LifeBuoy, MapPin, Package, Send, UserRound } from 'lucide-react';

export default function HelpDesk(){
 const [form,setForm]=useState({type:'Medical',location:'',details:''}); const [submitted,setSubmitted]=useState(false);
 const submit=(e)=>{e.preventDefault();setSubmitted(true)};
 if(submitted)return <div className="success-screen glass-panel"><div className="success-orb"><CheckCircle2 size={32}/></div><span className="eyebrow">Request received</span><h2>Help is now in the response queue.</h2><p>Your demo reference is <strong>RQ-1051</strong>. Keep your phone available and stay where responders can safely reach you.</p><div className="success-grid"><span><LifeBuoy size={15}/><b>Priority</b><small>High</small></span><span><MapPin size={15}/><b>Location</b><small>{form.location||'Shared location'}</small></span><span><UserRound size={15}/><b>Next step</b><small>Team assignment</small></span></div><button className="glass-cta" onClick={()=>setSubmitted(false)}>Create another request</button></div>;
 return <div className="content-stack"><div className="page-intro"><div><span className="eyebrow">Citizen emergency assistance</span><h2>Tell us what you need.</h2><p>Only share the information responders need. For immediate danger, call 112.</p></div><div className="urgent-pill"><span className="live-dot"/> Response teams online</div></div>
 <div className="help-layout"><form className="help-form glass-panel" onSubmit={submit}><div className="form-step"><span>01</span><div><strong>Type of assistance</strong><small>Choose the fastest route to the right team.</small></div></div><div className="help-options">{[['Medical','Need medical support','medical',HeartPulse],['Evacuation','Unsafe location','evacuation',Home],['Food & water','Essential supplies','food',Package],['Family support','Missing / separated person','family',UserRound]].map(([t,d,k,I])=><button type="button" key={t} className={`help-option ${form.type===t?'active':''}`} onClick={()=>setForm({...form,type:t})}><I size={18}/><div><strong>{t}</strong><small>{d}</small></div></button>)}</div>
 <div className="form-step"><span>02</span><div><strong>Where are you?</strong><small>A landmark makes dispatch faster.</small></div></div><label>Nearest location / landmark<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="e.g. Kothrud depot, near the bridge"/></label>
 <div className="form-step"><span>03</span><div><strong>Anything responders should know?</strong><small>Age, number of people, accessibility needs, medicine etc.</small></div></div><label>Details<textarea rows="5" value={form.details} onChange={e=>setForm({...form,details:e.target.value})} placeholder="Describe the situation in simple words..."/></label><button className="glass-cta full" type="submit"><Send size={16}/> Submit emergency request</button><div className="privacy-note"><Info size={14}/> Prototype only. Do not enter sensitive personal identifiers.</div></form>
 <aside className="help-aside"><section className="glass-panel emergency-card"><div className="emergency-badge">112</div><h3>Immediate danger?</h3><p>Do not wait for the form. Call emergency services when there is an immediate threat to life or safety.</p><button className="glass-cta full">Call 112</button></section><section className="glass-panel tips"><span className="eyebrow">Before you send</span><span><CheckCircle2 size={15}/> Keep one contact number reachable</span><span><CheckCircle2 size={15}/> Mention children, older adults or mobility needs</span><span><CheckCircle2 size={15}/> Use a landmark if you cannot share GPS</span></section></aside></div></div>
}
