import React, { useMemo, useState } from 'react';
import { CheckCircle2, ClipboardCheck, Filter, Flag, MapPin, MessageSquare, Search, ShieldAlert, Truck, UserRoundCheck } from 'lucide-react';
import { requests as seed } from '../lib/mockData';
import { useAuth } from '../context/AuthContext';

export default function Requests(){
 const {session}=useAuth(); const [items,setItems]=useState(seed); const [q,setQ]=useState(''); const [status,setStatus]=useState('all'); const [toast,setToast]=useState('');
 const list=useMemo(()=>items.filter(r=>(status==='all'||r.status.toLowerCase()===status)&&`${r.id} ${r.citizen} ${r.location} ${r.type}`.toLowerCase().includes(q.toLowerCase())),[items,q,status]);
 const advance=(id)=>{setItems(v=>v.map(r=>r.id===id?{...r,status:r.status==='Open'?'Verified':r.status==='Verified'?'Assigned':r.status==='Assigned'?'In transit':'Resolved'}:r));setToast('Request workflow advanced.');setTimeout(()=>setToast(''),2200)};
 return <div className="content-stack"><div className="page-intro"><div><span className="eyebrow">Operational queue</span><h2>{session.role==='ngo'?'Help your team move faster.':'Verify, dispatch and close requests.'}</h2><p>Role permissions control who can verify requests, assign teams and progress an incident.</p></div><div className="mini-kpis"><span><ShieldAlert size={14}/> 6 critical</span><span><Truck size={14}/> 9 in transit</span><span><CheckCircle2 size={14}/> 18 resolved</span></div></div>
 <div className="filter-bar glass-panel"><div className="filter-left"><Search size={15}/><input className="bare-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search request, person, location..."/><Filter size={15}/>{['all','open','verified','assigned','in transit','resolved'].map(x=><button key={x} className={status===x?'active':''} onClick={()=>setStatus(x)}>{x}</button>)}</div></div>
 <div className="request-table glass-panel"><div className="table-head"><span>Request</span><span>Priority</span><span>Status</span><span>Assigned team</span><span>Action</span></div>{list.map(r=><div className="table-row" key={r.id}><div className="request-person"><div className="request-avatar">{r.citizen[0]}</div><div><strong>{r.id} · {r.type}</strong><span>{r.citizen} · <MapPin size={12}/>{r.location} · {r.time}</span></div></div><span className={`tag ${r.priority.toLowerCase()}`}>{r.priority}</span><span className="status-text"><i className={`status-dot ${r.status.replace(' ','-').toLowerCase()}`}/>{r.status}</span><span className="team-text">{r.team}</span><button className="tiny-icon" onClick={()=>advance(r.id)} title="Advance workflow"><ClipboardCheck size={16}/></button></div>)}</div>
 <div className="request-side-grid"><section className="glass-panel request-guide"><div className="panel-head"><div><span className="panel-icon"><Flag size={16}/></span><strong>Response protocol</strong></div></div><p>Verify location, identify the immediate risk, assign the right response team and keep the requester informed.</p><div className="protocol-steps"><span><b>01</b> Verify</span><span><b>02</b> Dispatch</span><span><b>03</b> Update</span><span><b>04</b> Resolve</span></div></section><section className="glass-panel collaboration"><MessageSquare size={18}/><div><strong>Team channel</strong><p>Coordinate with field teams without leaving the incident queue.</p></div><button className="link-button">Open channel →</button></section></div>
 {toast&&<div className="inline-toast glass-panel">{toast}</div>}
 </div>
}
